apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-secret
  labels:
    app.kubernetes.io/name: {{ include "grafana-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  admin-password: {{ .Values.adminPassword | b64enc }}
