apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP  # Can be changed to NodePort or LoadBalancer if needed
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql