apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
      version: blue
  template:
    metadata:
      labels:
        app: nginx-app
        version: blue
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Replace with a specific version if needed
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-blue-config  # ConfigMap for blue version
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-blue-config
data:
  index.html: |
    <html>
    <head><title>Nginx Blue Version</title></head>
    <body>
      <h1>This is the Blue version of Nginx</h1>
    </body>
    </html>
