apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-hostpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostpath
  template:
    metadata:
      labels:
        app: hostpath
    spec:
      volumes:
      - name: host-logs
        hostPath:
          path: /mnt/pontakon
          type: DirectoryOrCreate
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: /var/log/nginx
          name: host-logs